services:

  rabbitmq:
    image: rabbitmq:4-management
    container_name: hermes-rabbitmq
    ports:
      - "127.0.0.1:5672:5672"  # AMQP
      - "127.0.0.1:15672:15672" # Management UI
    networks:
      - hermes-test

  mailpit:
    image: axllent/mailpit:latest
    container_name: hermes-mailpit
    ports:
      - "127.0.0.1:1025:1025"  # SMTP server
      - "127.0.0.1:8025:8025"  # Web UI
    environment:
      - MP_SMTP_BIND_ADDR=0.0.0.0:1025
      - MP_UI_BIND_ADDR=0.0.0.0:8025
    networks:
      - hermes-test

networks:
  hermes-test:
    driver: bridge
